### ISSUE TITLE
Add `--cheatsheet` option to `duckpan new` command. 

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/p5-app-duckpan#268]
Now that we've made it so easy to create a CheatSheet it seems like a `duckpan new --cheatsheet` command could help to make things a bit simpler. It should ideally generate the correct file, with the correct filename, in the correct location (/json). It could also pre-fill some of the info, or at least provide a skeleton of the document.

So far most developers seem to be doing OK, but this might be a useful tool if anyone wants to build it?

**Comment by srvsh** [comment]
@moollaza, if someone is not working on this already, may I try and do this one?

**Comment by moollaza** [comment]
@zachthompson did you have plans to work on this?

@srvsh AFAIKm no one else is working on this :+1:

**Comment by zachthompson** [comment]
Please do, @srvsh

**Comment by srvsh** [comment]
Thanks! I'll start work on this.

**Comment by zachthompson** [comment]
Thank you @srvsh!  We have wanted to be able to add general template processing to duckpan for a while.  If you want to open a PR early, we would be happy to follow your progress and provide feedback.

**Comment by srvsh** [comment]
@zachthompson thanks, I'll open a PR early on for feedback. Is there already some documentation about how general template processing is planned to be done? It'll be useful to ensure that my changes would fit in with the overall plan.

**Comment by zachthompson** [comment]
@srvsh I haven't looked at `App::DuckPAN::Cmd::New` in too much detail recently.  However, one maybe ideal goal would be to have the ability to add arbitrary template files and just have them work.  The `new` command will clearly need to be much more dynamic.

Give it a shot and let's see what happens!

**Comment by moollaza** [comment]
@srvsh there isn't any formal documentation on how the current templating works, but it can be reasoned from the code.

We have in the Spice and Goodies repos a "template" dir with some blank files that contain sections which are replaced.

The DuckPAN code takes user input, determines which repo you're currently in (Spice/Goodies), grabs the template file and then creates new files from the templates, placing them in the correct place, and fills them appropriate with the user input.

We *could* move the templates out of the repos, but then they need to be placed somewhere else that DuckPAN can access. Likely it's own /share/ directory?

**Comment by srvsh** [comment]
Thanks @zachthompson, @moollaza . Here's my proposal for this

* We can move the template information from DuckPAN.pm to a new YAML file.  There will be one such file for the different instant answer repositories.  Tentatively, I'm thinking of having it in `templates/templates.yml`. Here's the proposed file structure:
```
# file: zeroclickinfo-goodies/template/templates.yml
---
# templates for goodies

default:
    # template file. These are present in the 'template' subdirectory
    lib/DDG/Goodie/Example.pm:
        # output file. The string within {{..}} will be replaced
        # with a computed value. In this case, it'll be the 
        # instant answer's name in CamelCase
        lib/DDG/Goodie/{{ia_name_cc}}.pm
    t/Example.t:
        t/{{ia_name_cc}}.t

# a cheatsheet
cheatsheet:
    share/cheat_sheet.json:
        share/goodie/cheat_sheets/json/{{ia_name_lc}}.json
...
```
* Create a new `App::DuckPAN::Templates` class in the `p5-app-duckpan` repository. This would handle reading the `templates.yml` file to understand which templates can be use for the instant answer. This class would also handle creation of actual files from the templates. There would also have to be some logic to maintain backward compatibility for when the YAML file was absent. Apart from this, there would have to be methods to get a list of all template files since `App::DuckPAN::Restart` would need this to watch the containing directories for changes.

* Add a new optional `--template <template_name>` argument to the `new` command. That way, we know which template the user wants to use and create files accordingly. If this argument is not provided, we use the `default` template.

Thanks!
